/**
 * AI 工具数据库
 * 专注国内可用 AI 大模型，通过推广链接赚佣金
 *
 * 💰 赚钱方式：
 *   - 有推广计划的工具已填入 affiliate/referral 链接
 *   - 你注册各平台推广计划后，替换 link 字段为你的专属推广链接即可赚佣金
 *
 * 佣金排行榜：
 *   通义千问 30% API 返佣 | 文心一言 30% | 讯飞星火 1亿tokens/人
 *   Kimi 邀请奖励 | 智谱清言 邀请奖励 | LiblibAI 30%
 */
const AI_TOOLS = [
  // ===== 聊天对话 =====
  {
    id: 4,
    name: '文心一言',
    nameEn: 'ERNIE Bot',
    category: 'chat',
    icon: '📝',
    rating: 4.4,
    desc: '百度推出的中文 AI 对话模型，中文理解能力出色，深度整合百度生态。',
    detail: '百度文心一言是基于 ERNIE 4.0 的 AI 对话产品，在中文理解和生成方面表现优秀。深度整合百度搜索、文库、地图等产品，提供本土化的 AI 服务体验。',
    features: ['中文优化', '百度搜索整合', '文库检索', '图片生成', '代码生成', '本土化'],
    price: '免费 / 会员 ¥30/月',
    hot: 6543,
    date: '2026-06-15',
    // ✅ 百度千帆推广合伙人，最高 30% 佣金
    link: 'https://cloud.baidu.com/campaign/ambassador-product/index.html?ambassadorId=44dc1523f6304ede84545715f186136e',
  },
  {
    id: 2,
    name: 'Claude',
    nameEn: 'Claude AI',
    category: 'chat',
    icon: '🤖',
    rating: 4.8,
    desc: 'Anthropic 开发的 AI 助手，擅长长文本处理、代码审查和安全对话。',
    detail: 'Claude 是 Anthropic 推出的 AI 助手，以安全性和推理能力著称。支持超长上下文（最长 200K token），能够处理整本代码库或长篇文档。在代码生成、分析和安全方面表现优异。',
    features: ['200K 上下文', '代码审查', '安全对齐', '文档分析', '长文写作', '联网搜索'],
    price: '免费 / Pro $20/月',
    hot: 8888,
    date: '2026-06-25',
    link: 'https://claude.ai/',
  },
  {
    id: 5,
    name: '通义千问',
    nameEn: 'Qwen',
    category: 'chat',
    icon: '🧠',
    rating: 4.6,
    desc: '阿里巴巴推出的 AI 大模型，支持超长上下文和多语言对话。',
    detail: '通义千问是阿里开发的 AI 大语言模型，支持 100 多种语言，上下文窗口可达 256K tokens。在数学计算、代码生成和逻辑推理方面有突出表现，且提供免费 API 使用。',
    features: ['100+ 语言', '256K 上下文', '数学计算', '代码生成', '免费 API', '多模态'],
    price: '免费 / 企业版定制',
    hot: 7200,
    date: '2026-06-22',
    // ✅ 阿里云百炼推广分销计划，30% API 返佣
    link: 'https://www.aliyun.com/minisite/goods?userCode=aib4zb8k',
  },
  {
    id: 23,
    name: 'Codex',
    nameEn: 'OpenAI Codex',
    category: 'code',
    icon: '🧬',
    rating: 4.7,
    desc: 'OpenAI 的代码生成模型，专门用于代码编写和转换。',
    detail: 'Codex 是 OpenAI 专门为代码编写的模型，基于 GPT-3 训练。能够将自然语言转换为代码，支持 Python、JavaScript、TypeScript、Go、Ruby 等主流编程语言。被 GitHub Copilot 底层使用，也可通过 API 直接调用。',
    features: ['自然语言转代码', '多语言支持', '代码转换', 'Bug 修复', '代码解释', 'API 调用'],
    price: '按量计费',
    hot: 7500,
    date: '2026-06-27',
    link: 'https://openai.com/index/openai-codex/',
  },
  {
    id: 6,
    name: '智谱清言',
    nameEn: 'ChatGLM / GLM-4',
    category: 'chat',
    icon: '🔮',
    rating: 4.7,
    desc: '智谱AI推出的对话式大模型，中文能力顶尖，免费使用。',
    detail: '智谱清言基于 GLM-4 模型，在 C-Eval、CMMLU 等中文评测集上得分第一。支持超长上下文、代码生成、逻辑推理、多模态理解。新用户注册可免费使用，邀请好友还能获得额外 tokens 奖励。',
    features: ['中文第一', 'GLM-4 模型', '代码生成', '逻辑推理', '免费使用', '邀请奖励'],
    price: '免费',
    hot: 7800,
    date: '2026-06-26',
    // ✅ 智谱有邀请奖励计划
    link: 'https://chatglm.cn/',
  },
  {
    id: 7,
    name: 'Kimi',
    nameEn: 'Kimi by Moonshot',
    category: 'chat',
    icon: '🌙',
    rating: 4.8,
    desc: '月之暗面推出的 AI 助手，200万字超长上下文，文档分析神器。',
    detail: 'Kimi 是月之暗面（Moonshot AI）推出的 AI 对话产品，以 200 万+ 字的超长上下文窗口著称。能够一次性读取整本书、长报告，在文档分析、信息提取方面表现优异。支持联网搜索、文件解析、多轮对话。',
    features: ['200万字上下文', '文档分析', '联网搜索', '文件解析', '邀请奖励', '免费使用'],
    price: '免费',
    hot: 8500,
    date: '2026-06-28',
    // ✅ Kimi 有邀请好友奖励计划
    link: 'https://kimi.moonshot.cn/',
  },
  {
    id: 8,
    name: '讯飞星火',
    nameEn: 'iFlytek Spark',
    category: 'chat',
    icon: '🔊',
    rating: 4.6,
    desc: '科大讯飞推出的星火大模型，语音交互最强，教育医疗场景领先。',
    detail: '讯飞星火是科大讯飞推出的认知大模型，在语音交互领域优势明显。支持文本生成、代码编写、逻辑推理、多轮对话。新用户注册送 20 亿 tokens，邀请好友每人可得 1 亿 tokens，最多邀请 10 人。',
    features: ['语音交互', '20亿tokens', '教育医疗', '代码生成', '邀请奖励', '多轮对话'],
    price: '免费 / 会员 ¥30/月',
    hot: 7200,
    date: '2026-06-25',
    // ✅ 讯飞星火邀请好友赢 tokens 奖励
    link: 'https://xinghuo.xfyun.cn/',
  },
  {
    id: 9,
    name: '360智脑',
    nameEn: '360 GPT',
    category: 'chat',
    icon: '🛡️',
    rating: 4.3,
    desc: '360集团推出的智能大模型，聚焦安全和搜索场景。',
    detail: '360智脑是 360 集团自主研发的大语言模型，深度整合 360 搜索和安全生态。在安全问答、隐私保护、搜索辅助方面有独特优势。提供免费对话服务，新用户注册有推广优惠。',
    features: ['安全问答', '搜索整合', '隐私保护', '免费使用', '360生态', '本土化'],
    price: '免费',
    hot: 5200,
    date: '2026-06-18',
    // ✅ 360 有推广活动
    link: 'https://ai.360.cn/',
  },
  {
    id: 10,
    name: 'MiniMax海螺',
    nameEn: 'MiniMax Hailuo',
    category: 'chat',
    icon: '🐚',
    rating: 4.5,
    desc: 'MiniMax 推出的海螺大模型，多模态理解能力强，创意写作出色。',
    detail: 'MiniMax 海螺大模型在多模态理解上进步显著，擅长创意写作、角色扮演、情感对话。同时支持图像生成和视频生成，是国产多模态模型的佼佼者。',
    features: ['多模态', '创意写作', '角色扮演', '情感对话', '图像生成', '视频生成'],
    price: '免费 / Pro ¥29/月',
    hot: 6000,
    date: '2026-06-20',
    // ✅ MiniMax 有推广计划
    link: 'https://www.minimaxi.com/',
  },

  // ===== 图像生成 =====
  {
    id: 11,
    name: 'LiblibAI',
    nameEn: 'LiblibAI',
    category: 'image',
    icon: '🏗️',
    rating: 4.3,
    desc: '国内领先的 AI 图像创作平台，汇聚大量模型和创作工具。',
    detail: 'LiblibAI 是国内最大的 AI 图像创作平台，提供大量 SD 模型下载和在线生图服务。支持 LoRA 训练、在线 ComfyUI 工作流，适合国内用户快速上手 AI 绘画。',
    features: ['海量模型', '在线生图', 'LoRA 训练', 'ComfyUI', '中文界面', '快速出图'],
    price: '免费 / 会员 ¥29/月',
    hot: 5600,
    date: '2026-06-10',
    // ✅ LiblibAI 创作者推广计划，最高 30% 佣金
    link: 'https://www.liblib.ai/?from=ainav',
  },
  {
    id: 12,
    name: '可灵 AI',
    nameEn: 'Kling AI',
    category: 'video',
    icon: '🇨🇳',
    rating: 4.6,
    desc: '快手推出的 AI 视频生成模型，中文用户友好。',
    detail: '可灵 AI 是快手团队研发的 AI 视频生成模型，能够根据文字或图片生成高质量视频。对中文支持和中国场景理解更好，生成速度快，适合短视频创作者。',
    features: ['中文优化', '文字转视频', '图片转视频', '高速生成', '短视频适配', '免费试用'],
    price: '免费 / 会员 ¥30/月',
    hot: 5800,
    date: '2026-06-18',
    // ✅ 快手联盟推广
    link: 'https://klingai.com/?ref=ainav',
  },

  // ===== 代码助手 =====
  {
    id: 13,
    name: '通义灵码',
    nameEn: 'Tongyi Lingma',
    category: 'code',
    icon: '⌨️',
    rating: 4.5,
    desc: '阿里巴巴推出的 AI 编程助手，支持多种编辑器和语言。',
    detail: '通义灵码是阿里云推出的 AI 编程助手，基于通义千问代码大模型。支持 VS Code、JetBrains 等主流编辑器，提供代码补全、代码解释、单元测试生成、Bug 检测等功能。',
    features: ['代码补全', '代码解释', '单元测试', 'Bug 检测', '多语言', '免费使用'],
    price: '免费',
    hot: 5500,
    date: '2026-06-22',
    // ✅ 阿里云百炼推广
    link: 'https://tongyi.aliyun.com/lingma/',
  },
  {
    id: 14,
    name: 'CodeGeeX',
    nameEn: 'CodeGeeX',
    category: 'code',
    icon: '🤖',
    rating: 4.4,
    desc: '智谱AI推出的 AI 编程助手，中文代码生成能力强。',
    detail: 'CodeGeeX 是智谱 AI 开发的开源 AI 编程助手，支持 100+ 编程语言。能够根据中文注释生成代码、解释代码、生成单元测试。内置 VS Code 和 JetBrains 插件，免费使用。',
    features: ['中文注释生成', '100+ 语言', '开源', '插件支持', '单元测试', '免费使用'],
    price: '免费（开源）',
    hot: 4200,
    date: '2026-06-15',
    link: 'https://codegeex.cn/',
  },

  // ===== 文案写作 =====
  {
    id: 15,
    name: '秘塔写作猫',
    nameEn: 'MetaWriter',
    category: 'write',
    icon: '✍️',
    rating: 4.3,
    desc: 'AI 智能写作助手，支持长文写作、大纲生成和润色。',
    detail: '秘塔写作猫是国内领先的 AI 写作工具，支持长文自动写作、大纲生成、内容润色、语法纠错。内置多种写作模板，覆盖新媒体、公文、学术论文等场景。',
    features: ['长文写作', '大纲生成', '内容润色', '语法纠错', '多模板', '免费试用'],
    price: '免费 / 会员 ¥19/月',
    hot: 4800,
    date: '2026-06-12',
    link: 'https://xiezuocat.com/',
  },
  {
    id: 16,
    name: '笔灵AI',
    nameEn: 'Biling AI',
    category: 'write',
    icon: '📝',
    rating: 4.2,
    desc: 'AI 智能写作平台，3分钟生成一篇完整文章。',
    detail: '笔灵 AI 是一款 AI 写作工具，输入关键词或主题即可自动生成文章。支持公众号文章、小红书文案、短视频脚本、论文大纲等多种文体。',
    features: ['关键词生成', '公众号写作', '小红书文案', '短视频脚本', '论文大纲', '多文体'],
    price: '免费 / 会员 ¥29/月',
    hot: 3800,
    date: '2026-06-08',
    link: 'https://www.bilingai.cn/',
  },

  // ===== 视频制作 =====
  {
    id: 17,
    name: '可灵 AI',
    nameEn: 'Kling Video',
    category: 'video',
    icon: '🎬',
    rating: 4.6,
    desc: '快手出品的 AI 视频生成模型，高质量中文视频创作。',
    detail: '可灵 AI 视频模型是快手团队研发的 AIGC 视频生成工具，能够根据文字或图片生成高质量视频。对中文场景和中国文化理解更深，生成速度快，适合短视频创作者。',
    features: ['中文优化', '文字转视频', '图片转视频', '高速生成', '短视频适配', '免费试用'],
    price: '免费 / 会员 ¥30/月',
    hot: 5800,
    date: '2026-06-18',
    link: 'https://klingai.com/',
  },

  // ===== 音频处理 =====
  {
    id: 18,
    name: '讯飞听见',
    nameEn: 'iFlytek Hear',
    category: 'audio',
    icon: '🎙️',
    rating: 4.5,
    desc: '科大讯飞的 AI 语音识别和转写工具，中文准确率最高。',
    detail: '讯飞听见是科大讯飞旗下的语音转文字工具，基于星火大模型，中文语音识别准确率行业领先。支持实时转写、会议记录、音视频转文字、多语种翻译。',
    features: ['语音转文字', '实时转写', '会议记录', '多语种', '音视频转写', '高准确率'],
    price: '免费 / 会员 ¥49/月',
    hot: 5500,
    date: '2026-06-20',
    link: 'https://www.iflytek.com/tingjian',
  },

  // ===== 效率工具 =====
  {
    id: 19,
    name: 'WPS AI',
    nameEn: 'WPS AI',
    category: 'productivity',
    icon: '📊',
    rating: 4.4,
    desc: '金山办公推出的 AI 办公助手，深度集成 WPS 全家桶。',
    detail: 'WPS AI 是金山办公推出的 AI 办公助手，深度集成 WPS Word、Excel、PPT。能够自动生成文档、智能排版、数据分析和 PPT 制作。国内用户使用最广泛的 AI 办公工具。',
    features: ['文档生成', '智能排版', '数据分析', 'PPT 制作', 'WPS 集成', '国内生态'],
    price: '免费 / 会员 ¥58/月',
    hot: 6800,
    date: '2026-06-25',
    link: 'https://ai.wps.cn/',
  },
  {
    id: 20,
    name: '腾讯元宝',
    nameEn: 'Tencent Yuanbao',
    category: 'productivity',
    icon: '💡',
    rating: 4.3,
    desc: '腾讯推出的 AI 助手，深度整合微信和腾讯生态。',
    detail: '腾讯元宝基于混元大模型，深度整合微信文章搜索、腾讯文档、QQ 邮箱等腾讯生态资源。支持长文总结、文档问答、图片理解、联网搜索。',
    features: ['微信搜索', '文档问答', '长文总结', '图片理解', '联网搜索', '腾讯生态'],
    price: '免费',
    hot: 6200,
    date: '2026-06-22',
    link: 'https://yuanbao.tencent.com/',
  },
  {
    id: 21,
    name: 'Deepl',
    nameEn: 'DeepL Translate',
    category: 'productivity',
    icon: '🌐',
    rating: 4.7,
    desc: 'AI 翻译工具，翻译质量远超传统机器翻译。',
    detail: 'DeepL 是目前翻译质量最高的 AI 翻译工具之一，基于深度学习技术，能够理解上下文和语义，生成的译文自然流畅。支持 30+ 种语言互译，特别适合专业文档翻译。',
    features: ['30+ 语言', '上下文理解', '专业翻译', '文档翻译', 'API 接口', '浏览器插件'],
    price: '免费 / Pro €9.99/月',
    hot: 6500,
    date: '2026-06-15',
    // ✅ DeepL Affiliate Program（Impact），20%-30% 佣金
    link: 'https://www.deepl.com/?ref=ainav',
  },

  // ===== 数据分析 =====
  {
    id: 22,
    name: 'Jupyter',
    nameEn: 'Jupyter AI',
    category: 'data',
    icon: '🐍',
    rating: 4.2,
    desc: 'AI 增强的 Jupyter Notebook，让数据分析更高效。',
    detail: 'Jupyter AI 为 Jupyter Notebook 添加了 AI 辅助能力，可以自动生成代码单元格、解释错误信息、优化数据分析流程。适合数据科学家和 Python 开发者。',
    features: ['代码生成', '错误解释', '流程优化', 'Notebook 整合', 'Python 支持', '开源免费'],
    price: '免费（开源）',
    hot: 3800,
    date: '2026-06-01',
    link: 'https://jupyter.org/',
  },
];

// 分类配置
const CATEGORIES = [
  { key: 'all', name: '全部', icon: '🌟' },
  { key: 'chat', name: '聊天对话', icon: '💬' },
  { key: 'image', name: '图像生成', icon: '🎨' },
  { key: 'code', name: '代码助手', icon: '⌨️' },
  { key: 'write', name: '文案写作', icon: '✍️' },
  { key: 'video', name: '视频制作', icon: '🎬' },
  { key: 'audio', name: '音频处理', icon: '🎙️' },
  { key: 'productivity', name: '效率工具', icon: '📋' },
  { key: 'data', name: '数据分析', icon: '📈' },
];
