/**
 * AI 工具数据库
 * 每个工具包含：ID、名称、英文名、分类、图标、评分、描述、详细介绍、功能特性、价格、热度、日期、推广链接
 *
 * 💰 赚钱方式：
 *   - 有推广计划的工具已填入 affiliate/referral 链接
 *   - 无推广计划的工具保留官网链接
 *   - 你注册各平台推广计划后，替换 link 字段为你的专属推广链接即可赚佣金
 *
 * 佣金排行榜（按佣金比例）：
 *   Midjourney 30% 持续 | Suno 30% 持续 | Notion 30% 持续
 *   Jasper 30% 持续 | Copy.ai 30% 持续 | Runway 20% 持续
 *   DeepL 20%-30% | Gamma 20%-30% | ElevenLabs $5/人
 *   Cursor $20 credits/人 | GitHub Copilot $100 credits/人
 *   通义千问 30% API 返佣 | 文心一言 30% | LiblibAI 30%
 */
const AI_TOOLS = [
  // ===== 聊天对话 =====
  {
    id: 4,
    name: '文心一言',
    nameEn: 'ERNIE Bot',
    category: 'chat',
    icon: '📝',
    rating: 4.4,
    desc: '百度推出的中文 AI 对话模型，中文理解能力出色，深度整合百度生态。',
    detail: '百度文心一言是基于 ERNIE 4.0 的 AI 对话产品，在中文理解和生成方面表现优秀。深度整合百度搜索、文库、地图等产品，提供本土化的 AI 服务体验。',
    features: ['中文优化', '百度搜索整合', '文库检索', '图片生成', '代码生成', '本土化'],
    price: '免费 / 会员 ¥30/月',
    hot: 6543,
    date: '2026-06-15',
    // ✅ 百度千帆推广合伙人，最高 30% 佣金
    link: 'https://cloud.baidu.com/campaign/ambassador-product/index.html?ambassadorId=44dc1523f6304ede84545715f186136e',
  },
  {
    id: 5,
    name: '通义千问',
    nameEn: 'Qwen',
    category: 'chat',
    icon: '🧠',
    rating: 4.6,
    desc: '阿里巴巴推出的 AI 大模型，支持超长上下文和多语言对话。',
    detail: '通义千问是阿里开发的 AI 大语言模型，支持 100 多种语言，上下文窗口可达 256K tokens。在数学计算、代码生成和逻辑推理方面有突出表现，且提供免费 API 使用。',
    features: ['100+ 语言', '256K 上下文', '数学计算', '代码生成', '免费 API', '多模态'],
    price: '免费 / 企业版定制',
    hot: 7200,
    date: '2026-06-22',
    // ✅ 阿里云百炼推广分销计划，30% API 返佣
    link: 'https://www.aliyun.com/minisite/goods?userCode=aib4zb8k',
  },
  {
    id: 1,
    name: 'ChatGPT',
    nameEn: 'ChatGPT',
    category: 'chat',
    icon: '💬',
    rating: 4.9,
    desc: 'OpenAI 开发的 AI 对话助手，支持多轮对话、代码生成、数据分析等多种能力。',
    detail: 'ChatGPT 是目前最流行的 AI 对话模型，基于 GPT-4 架构，能够进行自然流畅的多轮对话，支持代码编写、数据分析、创意写作等多种任务。最新版本支持语音、图像理解和文件处理。',
    features: ['多轮对话', '代码生成', '文件分析', '图像理解', '语音交互', '插件扩展'],
    price: '免费 / Plus $20/月',
    hot: 9999,
    date: '2026-06-28',
    // ❌ 无推广计划，保留官网链接
    link: 'https://chat.openai.com/',
  },
  {
    id: 2,
    name: 'Claude',
    nameEn: 'Claude AI',
    category: 'chat',
    icon: '🤖',
    rating: 4.8,
    desc: 'Anthropic 开发的 AI 助手，擅长长文本处理、代码审查和安全对话。',
    detail: 'Claude 是 Anthropic 推出的 AI 助手，以安全性和推理能力著称。支持超长上下文（最长 200K token），能够处理整本代码库或长篇文档。在代码生成、分析和安全方面表现优异。',
    features: ['200K 上下文', '代码审查', '安全对齐', '文档分析', '长文写作', '联网搜索'],
    price: '免费 / Pro $20/月',
    hot: 8888,
    date: '2026-06-25',
    // ❌ 无推广计划，保留官网链接
    link: 'https://claude.ai/',
  },
  {
    id: 3,
    name: 'Gemini',
    nameEn: 'Google Gemini',
    category: 'chat',
    icon: '💎',
    rating: 4.7,
    desc: 'Google 的多模态 AI 模型，原生支持文本、图像、音频和视频理解。',
    detail: 'Google 最新的多模态 AI 模型，原生支持文本、图片、音频和视频的理解与生成。深度集成 Google 搜索生态，能够提供实时信息辅助回答。在视觉理解和逻辑推理方面表现出色。',
    features: ['多模态理解', 'Google 搜索集成', '实时信息', '视频分析', '逻辑推理', '免费使用'],
    price: '免费 / Ultra $20/月',
    hot: 7654,
    date: '2026-06-20',
    // ✅ Google AI 有合作伙伴计划
    link: 'https://aistudio.google.com/?utm_source=ainav',
  },

  // ===== 图像生成 =====
  {
    id: 6,
    name: 'Midjourney',
    nameEn: 'Midjourney',
    category: 'image',
    icon: '🎨',
    rating: 4.8,
    desc: '顶尖的 AI 图像生成工具，能够根据文字描述生成高质量艺术作品。',
    detail: 'Midjourney 是目前最强大的 AI 绘画工具之一，能够根据文字描述生成极具艺术感的图像。支持多种艺术风格，从写实照片到抽象艺术都能完美呈现。最新版本 v7 在细节控制和光影处理上大幅提升。',
    features: ['文字生成图像', '多种风格', '高清输出', '角色一致', '局部重绘', '社区分享'],
    price: '基础 $10/月',
    hot: 8500,
    date: '2026-06-27',
    // ✅ Midjourney Affiliate Program，30% 持续佣金（Impact 平台）
    link: 'https://www.midjourney.com/app?ref=ainav',
  },
  {
    id: 7,
    name: 'DALL·E',
    nameEn: 'DALL-E 3',
    category: 'image',
    icon: '🖼️',
    rating: 4.6,
    desc: 'OpenAI 开发的图像生成模型，精准理解复杂文字描述。',
    detail: 'DALL-E 3 是 OpenAI 最新的图像生成模型，与 ChatGPT 深度整合。能够精确理解复杂的文字描述，生成符合要求的图像。支持编辑已有图片和创建新图片，内置安全过滤。',
    features: ['精准描述理解', 'ChatGPT 整合', '图像编辑', '安全过滤', '多风格', '高分辨率'],
    price: 'ChatGPT Plus $20/月',
    hot: 7800,
    date: '2026-06-20',
    // ❌ 无独立推广计划（通过 ChatGPT Plus 使用）
    link: 'https://openai.com/dall-e-3',
  },
  {
    id: 8,
    name: 'Stable Diffusion',
    nameEn: 'Stable Diffusion XL',
    category: 'image',
    icon: '🌊',
    rating: 4.7,
    desc: '开源的 AI 图像生成模型，可本地部署，完全自由可控。',
    detail: 'Stable Diffusion 是最受欢迎的开源 AI 图像生成模型，可以在本地 GPU 上运行，完全免费且不受限制。拥有庞大的社区生态，支持 LoRA 微调、ControlNet 控制等多种高级功能。',
    features: ['完全开源', '本地部署', 'LoRA 微调', 'ControlNet', '免费使用', '社区生态'],
    price: '免费（开源）',
    hot: 7200,
    date: '2026-06-18',
    // ❌ 无官方推广计划（开源免费）
    link: 'https://stability.ai/',
  },
  {
    id: 9,
    name: 'FLUX',
    nameEn: 'FLUX AI',
    category: 'image',
    icon: '✨',
    rating: 4.7,
    desc: '新一代高性能 AI 图像生成模型，质量超越 Midjourney。',
    detail: 'FLUX 是由前 Stability AI 团队成员开发的全新 AI 图像生成模型，在多项评测中超越了 Midjourney 和 DALL-E 3。支持开源和商业使用，生成的图像质量极高。',
    features: ['超高画质', '开源可用', '文本渲染强', '光影真实', '速度快', '商用友好'],
    price: '免费 API / Pro $12/月',
    hot: 6800,
    date: '2026-06-26',
    // ❌ 无公开推广计划
    link: 'https://www.flux.ai/',
  },
  {
    id: 10,
    name: 'LiblibAI',
    nameEn: 'LiblibAI',
    category: 'image',
    icon: '🏗️',
    rating: 4.3,
    desc: '国内领先的 AI 图像创作平台，汇聚大量模型和创作工具。',
    detail: 'LiblibAI 是国内最大的 AI 图像创作平台，提供大量 SD 模型下载和在线生图服务。支持 LoRA 训练、在线 ComfyUI 工作流，适合国内用户快速上手 AI 绘画。',
    features: ['海量模型', '在线生图', 'LoRA 训练', 'ComfyUI', '中文界面', '快速出图'],
    price: '免费 / 会员 ¥29/月',
    hot: 5600,
    date: '2026-06-10',
    // ✅ LiblibAI 创作者推广计划，最高 30% 佣金
    link: 'https://www.liblib.ai/?from=ainav',
  },

  // ===== 代码助手 =====
  {
    id: 11,
    name: 'Cursor',
    nameEn: 'Cursor IDE',
    category: 'code',
    icon: '⌨️',
    rating: 4.9,
    desc: 'AI 原生代码编辑器，让编程像聊天一样简单高效。',
    detail: 'Cursor 是一款基于 AI 的代码编辑器，内置 Copilot++ 引擎，能够理解整个代码库并提供智能补全、代码重构、bug 修复等功能。支持自定义 AI 模型，可以接入 Claude、GPT-4 等。',
    features: ['AI 代码补全', '代码库理解', '多模型支持', '对话式编程', 'Bug 修复', '代码重构'],
    price: '免费 / Pro $20/月',
    hot: 8200,
    date: '2026-06-28',
    // ✅ Cursor Referral Program，推荐双方各获 $20 credits
    link: 'https://www.cursor.com/?ref=ainav',
  },
  {
    id: 12,
    name: 'GitHub Copilot',
    nameEn: 'GitHub Copilot',
    category: 'code',
    icon: '🐙',
    rating: 4.7,
    desc: 'GitHub 和 OpenAI 合作开发的 AI 编程助手，支持多种编辑器。',
    detail: 'GitHub Copilot 是最早也是最成熟的 AI 编程助手之一，支持 VS Code、JetBrains 等主流编辑器。能够根据注释生成代码、自动补全函数、解释代码逻辑。深度集成 GitHub 工作流。',
    features: ['多编辑器支持', '注释生成代码', '代码解释', 'Chat 模式', 'GitHub 整合', '团队协作'],
    price: '免费学生 / 个人 $10/月',
    hot: 7500,
    date: '2026-06-22',
    // ✅ GitHub Copilot Referral，推荐 Business/Enterprise 各获 $100 credits
    link: 'https://github.com/copilot?ref=ainav',
  },
  {
    id: 13,
    name: 'Windsurf',
    nameEn: 'Windsurf IDE',
    category: 'code',
    icon: '🌊',
    rating: 4.6,
    desc: '新一代 AI 编程 IDE，深度理解代码上下文。',
    detail: 'Windsurf 是 Codeium 推出的 AI 编程 IDE，采用 Cascade 技术深度理解代码上下文。不仅能补全代码，还能理解项目整体架构，进行跨文件的代码修改和重构。',
    features: ['Cascade 引擎', '跨文件理解', '自动重构', '项目级上下文', '实时协作', '免费基础版'],
    price: '免费 / Pro $15/月',
    hot: 5400,
    date: '2026-06-15',
    // ✅ Codeium 有合作伙伴计划
    link: 'https://windsurf.com/?ref=ainav',
  },
  {
    id: 14,
    name: 'Tabnine',
    nameEn: 'Tabnine',
    category: 'code',
    icon: '👆',
    rating: 4.4,
    desc: 'AI 代码补全工具，支持私有模型部署，注重代码安全。',
    detail: 'Tabnine 专注于 AI 代码补全，支持训练私有模型以确保代码安全。适合企业对代码隐私有严格要求的场景。支持多种编辑器和 CI/CD 集成。',
    features: ['私有模型', '代码安全', '多编辑器', 'CI/CD 集成', '团队管理', '自定义训练'],
    price: '免费 / Business $10/月',
    hot: 4200,
    date: '2026-06-08',
    // ✅ Tabnine Referral Program，双方获 credits
    link: 'https://www.tabnine.com/?ref=ainav',
  },

  // ===== 文案写作 =====
  {
    id: 15,
    name: 'Jasper',
    nameEn: 'Jasper AI',
    category: 'write',
    icon: '📄',
    rating: 4.5,
    desc: '专业的 AI 营销文案生成工具，帮助企业快速产出高质量内容。',
    detail: 'Jasper 是最早面向企业的 AI 文案生成工具，拥有超过 50 种文案模板，覆盖博客文章、广告文案、社交媒体帖子等多种场景。支持团队协作和内容审批流程。',
    features: ['50+ 模板', '博客写作', '广告文案', '社媒内容', '团队协作', '品牌语调'],
    price: '起步 $49/月',
    hot: 5800,
    date: '2026-06-12',
    // ✅ Jasper Affiliate Program（PartnerStack），30% 持续佣金
    link: 'https://www.jasper.ai/?ref=ainav',
  },
  {
    id: 16,
    name: 'Copy.ai',
    nameEn: 'Copy.ai',
    category: 'write',
    icon: '✍️',
    rating: 4.4,
    desc: 'AI 营销文案生成器，快速产出销售导向的内容。',
    detail: 'Copy.ai 专注于营销和销售场景的文案生成，拥有 90+ 模板。能够快速生成产品描述、邮件主题、广告标题等高转化内容。免费版即可满足个人用户需求。',
    features: ['90+ 模板', '产品描述', '邮件文案', '广告标题', '免费可用', '多语言'],
    price: '免费 / Pro $36/月',
    hot: 4800,
    date: '2026-06-10',
    // ✅ Copy.ai Affiliate Program（PartnerStack），30% 持续佣金
    link: 'https://www.copy.ai/?ref=ainav',
  },
  {
    id: 17,
    name: 'Notion AI',
    nameEn: 'Notion AI',
    category: 'write',
    icon: '📓',
    rating: 4.5,
    desc: 'Notion 内置的 AI 助手，辅助文档写作、总结和翻译。',
    detail: 'Notion AI 深度集成在 Notion 笔记应用中，能够在文档中直接使用 AI 进行写作辅助、内容总结、语法修正、翻译等操作。与 Notion 的工作流无缝衔接。',
    features: ['文档写作', '内容总结', '语法修正', '多语言翻译', '表格生成', '工作流整合'],
    price: '附加 $10/月',
    hot: 5200,
    date: '2026-06-18',
    // ✅ Notion Affiliate Program（PartnerStack），30% 持续佣金
    link: 'https://www.notion.so/product/ai?ref=ainav',
  },
  {
    id: 18,
    name: 'Writer',
    nameEn: 'Writer.com',
    category: 'write',
    icon: '🖊️',
    rating: 4.3,
    desc: '企业级 AI 内容管理平台，确保品牌一致性和合规性。',
    detail: 'Writer 是企业级 AI 内容管理平台，帮助大型组织统一管理 AI 生成内容，确保品牌语调一致性和合规性。支持自定义品牌知识库和术语表。',
    features: ['品牌一致性', '合规管理', '自定义知识库', '术语表', '团队协作', 'API 集成'],
    price: '企业定制',
    hot: 3200,
    date: '2026-06-05',
    // ❌ 无公开推广计划（企业定制为主）
    link: 'https://writer.com/',
  },

  // ===== 视频制作 =====
  {
    id: 19,
    name: 'Runway',
    nameEn: 'Runway ML',
    category: 'video',
    icon: '🎬',
    rating: 4.7,
    desc: 'AI 视频生成和编辑平台，让视频创作变得简单。',
    detail: 'Runway 是领先的 AI 视频创作平台，支持文字生成视频、视频编辑、物体移除、绿幕替换等专业功能。Gen-3 Alpha 模型能够生成电影级质量的视频片段。',
    features: ['文字生成视频', '视频编辑', '物体移除', '绿幕替换', '运动控制', '电影级质量'],
    price: '免费 / Plus $15/月',
    hot: 7600,
    date: '2026-06-26',
    // ✅ Runway Affiliate Program，20% 持续佣金
    link: 'https://runwayml.com/?ref=ainav',
  },
  {
    id: 20,
    name: 'Pika',
    nameEn: 'Pika Art',
    category: 'video',
    icon: '🎞️',
    rating: 4.5,
    desc: '简单易用的 AI 视频生成工具，支持图片和文字转视频。',
    detail: 'Pika 是一款简单易用的 AI 视频生成工具，可以将静态图片或文字描述转化为动态视频。支持角色 lip-sync（口型同步）、镜头控制和风格迁移。',
    features: ['图片转视频', '文字转视频', '口型同步', '镜头控制', '风格迁移', '社区创作'],
    price: '免费 / Pro $8/月',
    hot: 6200,
    date: '2026-06-20',
    // ✅ Pika Referral Program，推荐双方各获 50 credits
    link: 'https://pika.art/?ref=ainav',
  },
  {
    id: 21,
    name: '可灵 AI',
    nameEn: 'Kling AI',
    category: 'video',
    icon: '🇨🇳',
    rating: 4.6,
    desc: '快手推出的 AI 视频生成模型，中文用户友好。',
    detail: '可灵 AI 是快手团队研发的 AI 视频生成模型，能够根据文字或图片生成高质量视频。对中文支持和中国场景理解更好，生成速度快，适合短视频创作者。',
    features: ['中文优化', '文字转视频', '图片转视频', '高速生成', '短视频适配', '免费试用'],
    price: '免费 / 会员 ¥30/月',
    hot: 5800,
    date: '2026-06-18',
    // ✅ 快手联盟推广
    link: 'https://klingai.com/?ref=ainav',
  },
  {
    id: 22,
    name: 'Sora',
    nameEn: 'OpenAI Sora',
    category: 'video',
    icon: '🎥',
    rating: 4.8,
    desc: 'OpenAI 的 AI 视频生成模型，能创建逼真的长视频片段。',
    detail: 'Sora 是 OpenAI 发布的革命性视频生成模型，能够根据文字描述生成长达一分钟的高清视频。生成的视频具有惊人的物理真实感和镜头运动控制能力。',
    features: ['长视频生成', '物理真实', '镜头运动', '高清画质', '文字引导', '场景连贯'],
    price: 'ChatGPT Plus $20/月',
    hot: 8800,
    date: '2026-06-25',
    // ❌ 无独立推广计划（通过 ChatGPT Plus 使用）
    link: 'https://openai.com/sora',
  },

  // ===== 音频处理 =====
  {
    id: 23,
    name: 'ElevenLabs',
    nameEn: 'ElevenLabs',
    category: 'audio',
    icon: '🎙️',
    rating: 4.8,
    desc: '最自然的 AI 语音合成工具，支持多语种和声音克隆。',
    detail: 'ElevenLabs 是目前最自然的 AI 语音合成平台，支持 29 种语言，能够克隆任意声音。生成的语音几乎无法与自然语音区分，广泛应用于有声书、播客、视频配音等场景。',
    features: ['29 种语言', '声音克隆', '极自然语音', '情感控制', '多 speaker', 'API 接口'],
    price: '免费 / Starter $5/月',
    hot: 7400,
    date: '2026-06-24',
    // ✅ ElevenLabs Referral Program，每次推荐获 $5 credits
    link: 'https://elevenlabs.io/?ref=ainav',
  },
  {
    id: 24,
    name: 'Suno',
    nameEn: 'Suno AI',
    category: 'audio',
    icon: '🎵',
    rating: 4.6,
    desc: 'AI 音乐创作工具，输入文字就能生成完整歌曲。',
    detail: 'Suno 是革命性的 AI 音乐创作工具，只需输入歌词描述或主题，就能自动生成包含人声、乐器、编曲的完整歌曲。支持多种音乐风格和语言。',
    features: ['文字生成歌曲', '完整编曲', '多风格', '人声合成', '歌词生成', '商用授权'],
    price: '免费 / Pro $10/月',
    hot: 6800,
    date: '2026-06-22',
    // ✅ Suno Affiliate Program，30% 持续佣金
    link: 'https://suno.com/?ref=ainav',
  },
  {
    id: 25,
    name: 'Adobe Podcast',
    nameEn: 'Adobe Podcast AI',
    category: 'audio',
    icon: '🔊',
    rating: 4.4,
    desc: 'Adobe 出品的 AI 音频增强工具，一键提升录音质量。',
    detail: 'Adobe Podcast AI 是一组免费的 AI 音频处理工具，包括麦克风语音检测（去除背景噪音）、音频增强（提升清晰度）和录音转文字。让普通麦克风也能录出专业级音质。',
    features: ['降噪增强', '语音检测', '录音转文字', '免费使用', '网页版', '一键操作'],
    price: '免费',
    hot: 4500,
    date: '2026-06-10',
    // ❌ 免费工具，无推广计划
    link: 'https://podcast.adobe.com/',
  },

  // ===== 效率工具 =====
  {
    id: 26,
    name: 'Notion',
    nameEn: 'Notion',
    category: 'productivity',
    icon: '📋',
    rating: 4.6,
    desc: 'AI 增强的全能工作空间，集笔记、项目管理、数据库于一体。',
    detail: 'Notion 是最流行的全能工作空间工具，集成了笔记、文档、项目管理、数据库等多种功能。配合 Notion AI，可以实现智能写作、内容总结、任务自动分类等高效工作流。',
    features: ['笔记文档', '项目管理', '数据库', '模板市场', '团队协作', 'AI 增强'],
    price: '免费 / Plus $10/月',
    hot: 8000,
    date: '2026-06-27',
    // ✅ Notion Affiliate Program（PartnerStack），30% 持续佣金
    link: 'https://www.notion.so/?ref=ainav',
  },
  {
    id: 27,
    name: 'Mem',
    nameEn: 'Mem AI',
    category: 'productivity',
    icon: '🧩',
    rating: 4.3,
    desc: 'AI 驱动的知识管理系统，自动关联和整理你的笔记。',
    detail: 'Mem 是一款 AI 驱动的知识管理工具，能够自动学习和关联你的笔记内容，形成知识图谱。无需手动整理，AI 会自动为你建立笔记之间的联系，让知识管理变得 effortless。',
    features: ['自动关联', '知识图谱', '智能搜索', 'AI 总结', '无需整理', '隐私优先'],
    price: '免费 / Pro $12/月',
    hot: 3800,
    date: '2026-06-08',
    // ✅ Mem 有推荐计划
    link: 'https://www.mem.ai/?ref=ainav',
  },
  {
    id: 28,
    name: 'Deepl',
    nameEn: 'DeepL Translate',
    category: 'productivity',
    icon: '🌐',
    rating: 4.7,
    desc: 'AI 翻译工具，翻译质量远超传统机器翻译。',
    detail: 'DeepL 是目前翻译质量最高的 AI 翻译工具之一，基于深度学习技术，能够理解上下文和语义，生成的译文自然流畅。支持 30+ 种语言互译，特别适合专业文档翻译。',
    features: ['30+ 语言', '上下文理解', '专业翻译', '文档翻译', 'API 接口', '浏览器插件'],
    price: '免费 / Pro €9.99/月',
    hot: 6500,
    date: '2026-06-15',
    // ✅ DeepL Affiliate Program（Impact），20%-30% 佣金
    link: 'https://www.deepl.com/?ref=ainav',
  },
  {
    id: 29,
    name: 'Gamma',
    nameEn: 'Gamma App',
    category: 'productivity',
    icon: '📊',
    rating: 4.5,
    desc: 'AI 驱动的演示文稿和文档生成工具。',
    detail: 'Gamma 是一款 AI 驱动的演示文稿和文档生成工具，只需输入主题或大纲，就能自动生成精美的 PPT、文档或网页。支持丰富的模板和自定义编辑。',
    features: ['AI 生成 PPT', '文档生成', '网页创建', '丰富模板', '实时协作', '导出多种格式'],
    price: '免费 / Pro $10/月',
    hot: 5200,
    date: '2026-06-12',
    // ✅ Gamma Affiliate Program（PartnerStack），20%-30% 佣金
    link: 'https://gamma.app/?ref=ainav',
  },

  // ===== 数据分析 =====
  {
    id: 30,
    name: 'Tableau CRM',
    nameEn: 'Tableau Einstein',
    category: 'data',
    icon: '📈',
    rating: 4.4,
    desc: 'Salesforce 旗下的 AI 数据分析平台，智能洞察业务数据。',
    detail: 'Tableau CRM 是 Salesforce 旗下的 AI 数据分析平台，利用 Einstein AI 自动发现数据中的模式和洞察。支持自然语言查询，可以用对话方式分析数据。',
    features: ['自然语言查询', '自动洞察', '可视化报表', '预测分析', 'AI 推荐', '实时数据'],
    price: '企业定制',
    hot: 4200,
    date: '2026-06-05',
    // ❌ 企业定制为主，无个人推广计划
    link: 'https://www.salesforce.com/products/tableau/',
  },
  {
    id: 31,
    name: 'ThoughtSpot',
    nameEn: 'ThoughtSpot',
    category: 'data',
    icon: '🔎',
    rating: 4.3,
    desc: 'AI 搜索引擎式的数据分析平台，用搜索代替复杂查询。',
    detail: 'ThoughtSpot 将数据分析变成了搜索体验。用户可以用自然语言搜索数据，AI 自动生成图表和洞察。无需编写 SQL，任何人都可以进行数据分析。',
    features: ['搜索式分析', '自然语言', '自动图表', '预测洞察', '移动端', '零学习成本'],
    price: '免费试用 / 企业定制',
    hot: 3500,
    date: '2026-06-03',
    // ✅ ThoughtSpot 有合作伙伴计划
    link: 'https://www.thoughtspot.com/?ref=ainav',
  },
  {
    id: 32,
    name: 'Jupyter',
    nameEn: 'Jupyter AI',
    category: 'data',
    icon: '🐍',
    rating: 4.2,
    desc: 'AI 增强的 Jupyter Notebook，让数据分析更高效。',
    detail: 'Jupyter AI 为 Jupyter Notebook 添加了 AI 辅助能力，可以自动生成代码单元格、解释错误信息、优化数据分析流程。适合数据科学家和 Python 开发者。',
    features: ['代码生成', '错误解释', '流程优化', 'Notebook 整合', 'Python 支持', '开源免费'],
    price: '免费（开源）',
    hot: 3800,
    date: '2026-06-01',
    // ❌ 开源免费，无推广计划
    link: 'https://jupyter.org/',
  },
];

// 分类配置
const CATEGORIES = [
  { key: 'all', name: '全部', icon: '🌟' },
  { key: 'chat', name: '聊天对话', icon: '💬' },
  { key: 'image', name: '图像生成', icon: '🎨' },
  { key: 'code', name: '代码助手', icon: '⌨️' },
  { key: 'write', name: '文案写作', icon: '✍️' },
  { key: 'video', name: '视频制作', icon: '🎬' },
  { key: 'audio', name: '音频处理', icon: '🎙️' },
  { key: 'productivity', name: '效率工具', icon: '📋' },
  { key: 'data', name: '数据分析', icon: '📈' },
];
